apiVersion: v1
kind: Service
metadata:
  name: ants-tmlt-svc
spec:
  selector:
    app: ants-tmlt-svc
  ports:
  - protocol: "TCP"
    port: 8088
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ants-tmlt-svc
spec:
  selector:
    matchLabels:
      app: ants-tmlt-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: ants-tmlt-svc
    spec:
      containers:
      - name: ants-tmlt-svc
        image: us-central1-docker.pkg.dev/lunar-outlet-403221/antslift-docker/antslift-service-template:1.6.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: APP_LOG_APPENDER
          value: STDOUT
        - name: POSTGRES_JDBC_URL
          value: jdbc:postgresql://cluster-example-rw/app?sslmode=require
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              # Need to use superuser for now, otherwise ERROR: permission denied to set role "antslift_service_template (SQL State: 42501)
              # https://github.com/antslift-org/antslift-service-template/blob/6992312439ba8c9f5bdd3c4c7f42f5bbe5167ffa/src/main/resources/db/migration/beforeEachMigrate.sql#L25
              # For how superuser is defined, refer https://cloudnative-pg.io/documentation/current/applications/#secrets
              name: cluster-example-superuser
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-example-superuser
              key: password
